############# German navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Die Nekos"
url = "about/"
weight = 2

[[main]]
name = "Gallerie"
url = "gallery/"
weight = 3


# FC content
[[main]]
name = "Die FC"
hasChildren = true
weight = 4

[[main]]
weight = 1
parent = "Die FC"
name = "ğŸ“œ Blog"
url = "blog/"

[[main]]
weight = 2
parent = "Die FC"
name = "ğŸ“… Events"
url = "events/"


# Plots
[[main]]
weight = 5
name = "Plots"
hasChildren = true

[[main]]
weight = 1
parent = "Plots"
name = "ğŸ± KatzenkÃ¶rbchen"
url = "plot_katzenkoerbchen/"

[[main]]
weight = 2
parent = "Plots"
name = "ğŸ­ Events"
url = "plot_events/"

[[main]]
weight = 3
parent = "Plots"
name = "ğŸ» Taverne"
url = "plot_taverne/"

# footer menu
[[footer]]
name = "Die Nekos"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Impressum"
url = "privacy-policy/"
weight = 3
