############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Nekos"
url = "about/"
weight = 2

[[main]]
name = "ğŸ“· Gallery"
url = "gallery/"
weight = 3


# FC content
[[main]]
name = "âšœï¸ Free Company"
hasChildren = true
weight = 4

[[main]]
weight = 1
parent = "âšœï¸ Free Company"
name = "ğŸ“œ Adventures"
url = "blog/"

[[main]]
weight = 1
parent = "âšœï¸ Free Company"
name = "ğŸ“… Events"
url = "events/"


# Plots
[[main]]
weight = 5
name = "Plots"
url = "plots/"

# footer menu
[[footer]]
name = "Members"
url = "about/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
